id: I2EA0CD8E
legacy_id: P005412
ocr_import_info:
  bdrc_scan_id: W1KG3643
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T06:30:27'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T15:10:54.425483+00:00'
last_modified: 2022-08-31 23:11:32.940626
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG3643
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG3643
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཚད་མ་རྣམ་ངེས་ཀྱི་འགྲེལ་ཆེན་ལས་མཚན་དོན་ཟུར་དུ་བཀོལ་བ་སོགས་ཆོས་ཚན་ཁག་ཅིག
  author: བུ་སྟོན་རིན་ཆེན་གྲུབ།
statistics:
  ocr_word_mean_confidence_index: 0.7340741442386264
  ocr_word_median_confidence_index: 0.7799999713897705
quality: null
bases:
  I1KG3651:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG3651
      total_pages: 1068
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG3651.txt
    statistics:
      ocr_word_median_confidence_index: 0.7799999713897705
      ocr_word_mean_confidence_index: 0.7340741442386264
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
