id: I2EA0CD8E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T06:37:27+00:00'
last_modified: '2022-06-08T02:54:13.494423+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG3643
  title: ཚད་མ་རྣམ་ངེས་ཀྱི་འགྲེལ་ཆེན་ལས་མཚན་དོན་ཟུར་དུ་བཀོལ་བ་སོགས་ཆོས་ཚན་ཁག་ཅིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    9B87:
      image_group_id: I1KG3651
      title: ''
      total_pages: 1068
      order: 1
      base_file: 9B87.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
